Added `backdrop` prop to `Dialog`
equinor/webviz-core-components pull request #210
Opened 2022-02-24 16:19 UTC by rubenthoms

This allows to disable the backdrop behind a dialog and makes all other elements remain clickable.

Closes #209.

2022-02-24 16:51 UTC, anders-kiaer approved these changes
:+1:

2022-02-24 17:40 UTC, HansKallekleiv requested changes
There is an issue when used in Webviz:

With backdrop it looks ok:
![image](https://user-images.githubusercontent.com/16436291/155577751-8971f76e-f11e-42f8-a790-f9527587b904.png)

Without backdrop it still blurs the part of the viewport(sidebar?).
![image](https://user-images.githubusercontent.com/16436291/155577539-0dbcfe52-7a20-4169-938b-bf92931e4328.png)

2022-02-25 10:23 UTC, HansKallekleiv commented
Cannot reproduce my bug after upgrading all packages. Approved :)

2022-02-25 10:23 UTC, HansKallekleiv approved these changes

2022-02-25 10:40 UTC, merged