Refactoring: converted to TypeScript
equinor/webviz-core-components pull request #86
Opened 2021-02-18 15:23 UTC by rubenthoms

Adjusted build environment and converted all files to TypeScript except for the main component files (changed those to JSX).

2021-02-22 09:11 UTC, HansKallekleiv requested changes

2021-02-22 09:11 UTC, HansKallekleiv commented on src/lib/components/Select/Select.jsx
> +const Select = ({ id, size, options, value, multi, className, style, parent_className, parent_style, setProps, persistence, persisted_props, persistence_type }) => {
too long line?

2021-02-22 09:11 UTC, HansKallekleiv commented on src/lib/components/WebvizPluginPlaceholder/WebvizPluginPlaceholder.jsx
> +const WebvizPluginPlaceholder = ({ id, children, buttons, contact_person, download, screenshot_filename, tour_steps, data_requested, setProps }) => {
too long line?

2021-02-22 14:18 UTC, HansKallekleiv approved these changes
LGTM 👍

2021-03-01 14:20 UTC, asnyv commented on .babelrc
> +}
newline

2021-03-09 16:09 UTC, merged