Fix for #98 - Download file not working
equinor/webviz-core-components pull request #99
Opened 2021-03-25 12:41 UTC by rubenthoms

Closes #98.

2021-03-25 13:45 UTC, asnyv requested changes

2021-03-25 13:45 UTC, asnyv commented on CHANGELOG.md
> +### Bugfix
To keep in line with other webviz-repos
```suggestion
### Fixed
```

2021-03-25 14:42 UTC, anders-kiaer commented on CHANGELOG.md
> +- [#99](https://github.com/equinor/webviz-core-components/pull/99) - Fixed bug which prevented using the download button in WebvizPluginPlaceholder and started to download when compontent was mountin
```suggestion
- [#99](https://github.com/equinor/webviz-core-components/pull/99) - Fixed bug which prevented using the download button in `WebvizPluginPlaceholder` and started to download when component was mounting. 
```

2021-03-26 10:17 UTC, asnyv approved these changes

2021-03-26 10:43 UTC, merged